"""Phase 1 — projects, app_spec_versions, build_plan_versions.

Revision ID: 0001_phase1_projects
Revises:
Create Date: 2026-04-22

Hand-authored (not autogenerated) because Phase 1 first slice ships before
the sandbox has a running Postgres for autogenerate to introspect. This
matches `app.models.project` exactly — keep them in sync.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0001_phase1_projects"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "projects",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("tenant_id", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("original_prompt", sa.Text(), nullable=False),
        sa.Column("current_spec_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("current_plan_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("tenant_id", "slug", name="uq_projects_tenant_slug"),
    )
    op.create_index("ix_projects_tenant_id", "projects", ["tenant_id"])
    op.create_index("ix_projects_slug", "projects", ["slug"])
    op.create_index("ix_projects_current_spec_id", "projects", ["current_spec_id"])
    op.create_index("ix_projects_current_plan_id", "projects", ["current_plan_id"])
    op.create_index("ix_projects_tenant_created", "projects", ["tenant_id", "created_at"])

    op.create_table(
        "app_spec_versions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("project_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("tenant_id", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("sha", sa.String(length=64), nullable=False),
        sa.Column("spec_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("origin", sa.String(length=32), nullable=False, server_default="agent"),
        sa.Column("model_name", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"]),
        sa.UniqueConstraint("project_id", "version", name="uq_spec_versions_project_version"),
    )
    op.create_index("ix_app_spec_versions_project_id", "app_spec_versions", ["project_id"])
    op.create_index("ix_app_spec_versions_tenant_id", "app_spec_versions", ["tenant_id"])
    op.create_index("ix_app_spec_versions_sha", "app_spec_versions", ["sha"])

    op.create_table(
        "build_plan_versions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("project_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("tenant_id", sa.String(length=255), nullable=False),
        sa.Column("spec_version_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("sha", sa.String(length=64), nullable=False),
        sa.Column("plan_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model_name", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False, server_default="proposed"),
        sa.Column("extra", sa.JSON(), nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"]),
        sa.ForeignKeyConstraint(["spec_version_id"], ["app_spec_versions.id"]),
        sa.UniqueConstraint("project_id", "version", name="uq_plan_versions_project_version"),
    )
    op.create_index("ix_build_plan_versions_project_id", "build_plan_versions", ["project_id"])
    op.create_index("ix_build_plan_versions_tenant_id", "build_plan_versions", ["tenant_id"])
    op.create_index("ix_build_plan_versions_sha", "build_plan_versions", ["sha"])


def downgrade() -> None:
    op.drop_index("ix_build_plan_versions_sha", table_name="build_plan_versions")
    op.drop_index("ix_build_plan_versions_tenant_id", table_name="build_plan_versions")
    op.drop_index("ix_build_plan_versions_project_id", table_name="build_plan_versions")
    op.drop_table("build_plan_versions")

    op.drop_index("ix_app_spec_versions_sha", table_name="app_spec_versions")
    op.drop_index("ix_app_spec_versions_tenant_id", table_name="app_spec_versions")
    op.drop_index("ix_app_spec_versions_project_id", table_name="app_spec_versions")
    op.drop_table("app_spec_versions")

    op.drop_index("ix_projects_tenant_created", table_name="projects")
    op.drop_index("ix_projects_current_plan_id", table_name="projects")
    op.drop_index("ix_projects_current_spec_id", table_name="projects")
    op.drop_index("ix_projects_slug", table_name="projects")
    op.drop_index("ix_projects_tenant_id", table_name="projects")
    op.drop_table("projects")
