"""Auth router for the generated FastAPI app — JWT block.

Exposes:
    POST /api/v1/auth/login    — OAuth2 password-flow token issue.
    POST /api/v1/auth/register — signup, gated on `ALLOW_SIGNUP=true`.
    GET  /api/v1/auth/me       — return the resolved `current_user`.

The `User` model is generated by the scaffolder; we resolve it lazily
to keep this file decoupled from the rest of the project.
"""

from __future__ import annotations

import os
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.security import OAuth2PasswordRequestForm
from pydantic import BaseModel, EmailStr
from sqlmodel import Session, select

from app.core.jwt_auth import (
    current_user,
    hash_password,
    issue_token,
    verify_password,
)

router = APIRouter(prefix="/api/v1/auth", tags=["auth"])


def _get_session_dep() -> Any:
    from app.core.db import get_session  # type: ignore[import-not-found]

    return get_session


def _get_user_model() -> Any:
    from app.models.user import User  # type: ignore[import-not-found]

    return User


class TokenResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"


class RegisterRequest(BaseModel):
    email: EmailStr
    password: str


class UserPublic(BaseModel):
    id: str
    email: EmailStr
    is_active: bool = True


def _allow_signup() -> bool:
    return os.environ.get("ALLOW_SIGNUP", "true").lower() in {"1", "true", "yes"}


@router.post("/login", response_model=TokenResponse)
def login(
    form: OAuth2PasswordRequestForm = Depends(),
    session: Session = Depends(_get_session_dep()),
) -> TokenResponse:
    UserModel = _get_user_model()
    user = session.exec(select(UserModel).where(UserModel.email == form.username)).first()
    if user is None or not verify_password(form.password, getattr(user, "hashed_password", "")):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Incorrect email or password",
            headers={"WWW-Authenticate": "Bearer"},
        )
    if getattr(user, "is_active", True) is False:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Account disabled",
        )
    return TokenResponse(access_token=issue_token(user.id))


@router.post("/register", response_model=TokenResponse, status_code=status.HTTP_201_CREATED)
def register(
    body: RegisterRequest,
    session: Session = Depends(_get_session_dep()),
) -> TokenResponse:
    if not _allow_signup():
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Signup is disabled",
        )
    UserModel = _get_user_model()
    existing = session.exec(select(UserModel).where(UserModel.email == body.email)).first()
    if existing is not None:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="Email already registered",
        )
    user = UserModel(email=body.email, hashed_password=hash_password(body.password))
    session.add(user)
    session.commit()
    session.refresh(user)
    return TokenResponse(access_token=issue_token(user.id))


@router.get("/me", response_model=UserPublic)
def me(user: Any = Depends(current_user)) -> UserPublic:
    return UserPublic(
        id=str(user.id),
        email=user.email,
        is_active=getattr(user, "is_active", True),
    )
